[1] [2020-07-16 11:27:13.383] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-16 11:27:13.384] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-16 11:27:13.386] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-16 11:27:13.386] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-16 11:29:14.445] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-16 11:29:14.447] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-16 11:29:14.449] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-16 11:29:14.449] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-16 11:46:27.002] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-16 11:46:27.112] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-16 11:46:27.113] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-16 11:46:27.114] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-16 11:46:27.114] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-16 11:46:27.114] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-16 11:46:27.134] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-16 11:46:27.137] [                                        ] OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.   (MySQL.py:653)
[4] [2020-07-16 11:46:27.140] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-16 11:46:27.140] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-16 11:51:10.183] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-16 11:51:10.184] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-16 11:51:10.187] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-16 11:51:10.187] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-16 11:51:40.635] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-16 11:51:40.637] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-16 11:51:40.639] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-16 11:51:40.639] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-16 13:53:40.703] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-16 13:53:40.800] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-16 13:53:40.800] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-16 13:53:40.801] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-16 13:53:40.801] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-16 13:53:40.801] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-16 13:53:40.805] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-16 13:53:40.810] [                                        ] OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.   (MySQL.py:653)
[4] [2020-07-16 13:53:40.812] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-16 13:53:40.813] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-20 09:19:09.023] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-20 09:19:09.026] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-20 09:19:09.028] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-20 09:19:09.028] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-20 09:23:39.162] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-20 09:23:39.282] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-20 09:23:39.282] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-20 09:23:39.282] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-20 09:23:39.283] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-20 09:23:39.283] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-20 09:23:39.286] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-20 09:23:39.291] [                                        ] OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.   (MySQL.py:653)
[4] [2020-07-20 09:23:39.293] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-20 09:23:39.293] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-20 09:26:26.119] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-20 09:26:26.156] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-20 09:26:26.158] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-20 09:26:26.158] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-20 17:07:49.584] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-20 17:07:49.694] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-20 17:07:49.695] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-20 17:07:49.695] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-20 17:07:49.696] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-20 17:07:49.696] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-20 17:07:49.701] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-20 17:07:49.707] [                                        ] OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.   (MySQL.py:653)
[4] [2020-07-20 17:07:49.709] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-20 17:07:49.710] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-20 17:40:37.254] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-20 17:40:37.255] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-20 17:40:37.258] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-20 17:40:37.258] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-20 17:41:21.515] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-20 17:41:21.614] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-20 17:41:21.614] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-20 17:41:21.615] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-20 17:41:21.615] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-20 17:41:21.615] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-20 17:41:21.626] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-20 17:41:21.628] [                                        ] OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.   (MySQL.py:653)
[4] [2020-07-20 17:41:21.641] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-20 17:41:21.641] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-20 17:45:36.810] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-20 17:45:36.930] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-20 17:45:36.937] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-20 17:45:36.937] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-20 17:45:36.937] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-20 17:45:36.938] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-20 17:45:36.947] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-20 17:45:36.949] [                                        ] OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.   (MySQL.py:653)
[4] [2020-07-20 17:45:36.951] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-20 17:45:36.951] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-21 09:28:57.591] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-21 09:28:57.729] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-21 09:28:57.730] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-21 09:28:57.731] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-21 09:28:57.731] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-21 09:28:57.732] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-21 09:28:57.737] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-21 09:28:57.746] [                                        ] OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.   (MySQL.py:653)
[4] [2020-07-21 09:28:57.748] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-21 09:28:57.748] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-21 09:29:41.353] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-21 09:29:41.355] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-21 09:29:41.357] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-21 09:29:41.357] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-21 09:46:59.881] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-21 09:47:00.046] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-21 09:47:00.048] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-21 09:47:00.049] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-21 09:47:00.049] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-21 09:47:00.049] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-21 09:47:00.052] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-21 09:47:00.055] [                                        ] OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.   (MySQL.py:653)
[4] [2020-07-21 09:47:00.058] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-21 09:47:00.058] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-21 09:51:00.950] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-21 09:51:01.149] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-21 09:51:01.150] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-21 09:51:01.152] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-21 09:51:01.152] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-21 09:51:01.163] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-21 09:51:01.168] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-21 09:51:01.172] [                                        ] OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.   (MySQL.py:653)
[4] [2020-07-21 09:51:01.182] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-21 09:51:01.182] [                                        ] "getpwnam(): name not found: 'opsiconfd'"   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 94, in __init__
    self.__fileUid = pwd.getpwnam(self.__fileUser)[2]
KeyError: "getpwnam(): name not found: 'opsiconfd'"
[1] [2020-07-21 09:52:03.829] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-21 09:52:04.055] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-21 09:52:04.059] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-21 09:52:04.070] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-21 09:52:04.071] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-21 09:52:04.071] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-21 09:52:04.076] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-21 09:52:04.083] [                                        ] OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.   (MySQL.py:653)
[3] [2020-07-21 09:52:04.170] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-21 09:52:04.178] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-21 09:52:04.178] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-21 09:52:04.240] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-21 09:52:04.240] [                                        ] Failed to bind to socket '/var/run/opsipxeconfd/opsipxeconfd.socket': [Errno 13] Permission denied   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 143, in _createUnixSocket
    self._socket.bind(self.config['port'])
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 198, in run
    self._createSocket()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 135, in _createSocket
    return self._createUnixSocket()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 145, in _createUnixSocket
    raise Exception(u"Failed to bind to socket '%s': %s" % (self.config['port'], error))
Exception: Failed to bind to socket '/var/run/opsipxeconfd/opsipxeconfd.socket': [Errno 13] Permission denied
[4] [2020-07-21 09:52:04.241] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-21 09:52:04.241] [                                        ] [Errno 2] No such file or directory: '/var/lib/opsi/config/depots'   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 648, in run
    self._opsipxeconfd._backend.configState_getClientToDepotserver(depotIds=[self._opsipxeconfd.config['depotId']])]
  File "<string>", line 1, in configState_getClientToDepotserver
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 137, in _executeMethod
    return meth(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 926, in configState_getClientToDepotserver
    depotIds = self.host_getIdents(type='OpsiDepotserver', id=depotIds)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 206, in host_getIdents
    return [host.getIdent(returnType) for host in self.host_getObjects(attributes=['id'], **filter)]
  File "<string>", line 1, in host_getObjects
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 137, in _executeMethod
    return meth(**kwargs)
  File "<string>", line 1, in host_getObjects
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 198, in _dispatchMethod
    res = meth(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 1261, in host_getObjects
    result = self._read('OpsiDepotserver', attributes, **filter)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 778, in _read
    for ident in self._getIdents(objType, **filter):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 452, in _getIdents
    for entry in os.listdir(self.__depotConfigDir):
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/opsi/config/depots'
[1] [2020-07-22 17:25:44.168] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-22 17:25:44.173] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:25:44.359] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:25:44.360] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-22 17:25:44.365] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-22 17:25:44.365] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-22 17:25:44.365] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-22 17:25:44.370] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-22 17:25:44.407] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-22 17:25:44.408] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-22 17:25:44.408] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-22 17:25:44.449] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-22 17:25:44.450] [                                        ] Failed to bind to socket '/var/run/opsipxeconfd/opsipxeconfd.socket': [Errno 2] No such file or directory   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 143, in _createUnixSocket
    self._socket.bind(self.config['port'])
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 198, in run
    self._createSocket()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 135, in _createSocket
    return self._createUnixSocket()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 145, in _createUnixSocket
    raise Exception(u"Failed to bind to socket '%s': %s" % (self.config['port'], error))
Exception: Failed to bind to socket '/var/run/opsipxeconfd/opsipxeconfd.socket': [Errno 2] No such file or directory
[4] [2020-07-22 17:25:44.450] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-22 17:25:44.450] [                                        ] [Errno 2] No such file or directory: '/var/lib/opsi/config/depots'   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 648, in run
    self._opsipxeconfd._backend.configState_getClientToDepotserver(depotIds=[self._opsipxeconfd.config['depotId']])]
  File "<string>", line 1, in configState_getClientToDepotserver
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 137, in _executeMethod
    return meth(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 926, in configState_getClientToDepotserver
    depotIds = self.host_getIdents(type='OpsiDepotserver', id=depotIds)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 206, in host_getIdents
    return [host.getIdent(returnType) for host in self.host_getObjects(attributes=['id'], **filter)]
  File "<string>", line 1, in host_getObjects
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 137, in _executeMethod
    return meth(**kwargs)
  File "<string>", line 1, in host_getObjects
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 198, in _dispatchMethod
    res = meth(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 1261, in host_getObjects
    result = self._read('OpsiDepotserver', attributes, **filter)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 778, in _read
    for ident in self._getIdents(objType, **filter):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 452, in _getIdents
    for entry in os.listdir(self.__depotConfigDir):
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/opsi/config/depots'
[1] [2020-07-22 17:27:04.406] [                                        ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-22 17:27:04.407] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:27:04.517] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:27:04.518] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:133: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-22 17:27:04.518] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-22 17:27:04.518] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-22 17:27:04.518] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-22 17:27:04.521] [                                        ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/opsicommon/logging/logging.py:175: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-22 17:27:04.535] [                                        ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-22 17:27:04.535] [                                        ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-22 17:27:04.535] [                                        ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-22 17:27:04.550] [                                        ] OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.   (MySQL.py:653)
[2] [2020-07-22 17:27:04.550] [                                        ] [Errno 2] No such file or directory: '/var/lib/opsi/config/depots'   (logging.py:177)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 648, in run
    self._opsipxeconfd._backend.configState_getClientToDepotserver(depotIds=[self._opsipxeconfd.config['depotId']])]
  File "<string>", line 1, in configState_getClientToDepotserver
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 137, in _executeMethod
    return meth(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 926, in configState_getClientToDepotserver
    depotIds = self.host_getIdents(type='OpsiDepotserver', id=depotIds)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 206, in host_getIdents
    return [host.getIdent(returnType) for host in self.host_getObjects(attributes=['id'], **filter)]
  File "<string>", line 1, in host_getObjects
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Base/Extended.py", line 137, in _executeMethod
    return meth(**kwargs)
  File "<string>", line 1, in host_getObjects
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 198, in _dispatchMethod
    res = meth(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 1261, in host_getObjects
    result = self._read('OpsiDepotserver', attributes, **filter)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 778, in _read
    for ident in self._getIdents(objType, **filter):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/File.py", line 452, in _getIdents
    for entry in os.listdir(self.__depotConfigDir):
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/opsi/config/depots'
[1] [2020-07-22 17:47:09,777.777] [               ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-22 17:47:09,884.884] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:47:09,890.890] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-22 17:47:09,891.891] [               ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-22 17:47:09,891.891] [               ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-22 17:47:09,891.891] [               ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-22 17:47:09,900.900] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:47:09,900.900] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:47:10,912.912] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:47:11,928.928] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:47:12,946.946] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:47:13,960.960] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:47:14,974.974] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:47:15,995.995] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:47:17,013.013] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:47:18,028.028] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:47:18,029.029] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-22 17:47:18,029.029] [               ] Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")   (Logger.py:94)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 230, in _createConnectionPool
    recycle=self._connectionPoolRecyclingSeconds,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 121, in __init__
    con = ConnectionPool.__instance.connect()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 264, in <lambda>
    return lambda crec: creator()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 118, in getConnection
    return MySQLdb.connect(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 581, in __init__
    self._sql = MySQL(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 187, in __init__
    self._createConnectionPool()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 244, in _createConnectionPool
    raise BackendUnableToConnectError(u"Failed to connect to database '%s' address '%s': %s" % (self._database, address, error))
OPSI.Exceptions.BackendUnableToConnectError: Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")
[1] [2020-07-22 17:47:28,798.798] [               ] logger port: tests/test_data/output/opsipxeconfd.socket   (opsipxeconfd.py:785)
[1] [2020-07-22 17:51:26,359.359] [               ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-22 17:51:26,462.462] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:51:26,462.462] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-22 17:51:26,463.463] [               ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-22 17:51:26,463.463] [               ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-22 17:51:26,463.463] [               ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-22 17:51:26,471.471] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:51:26,471.471] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:51:27,485.485] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:51:28,506.506] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:51:29,525.525] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:51:30,538.538] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:51:31,557.557] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:51:32,571.571] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:51:33,586.586] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:51:34,605.605] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:51:34,606.606] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-22 17:51:34,606.606] [               ] Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")   (Logger.py:94)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 230, in _createConnectionPool
    recycle=self._connectionPoolRecyclingSeconds,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 121, in __init__
    con = ConnectionPool.__instance.connect()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 264, in <lambda>
    return lambda crec: creator()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 118, in getConnection
    return MySQLdb.connect(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 581, in __init__
    self._sql = MySQL(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 187, in __init__
    self._createConnectionPool()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 244, in _createConnectionPool
    raise BackendUnableToConnectError(u"Failed to connect to database '%s' address '%s': %s" % (self._database, address, error))
OPSI.Exceptions.BackendUnableToConnectError: Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")
[1] [2020-07-22 17:51:45,383.383] [               ] logger port: tests/test_data/output/opsipxeconfd.socket   (opsipxeconfd.py:785)
[1] [2020-07-22 17:54:03,422.422] [               ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-22 17:54:03,527.527] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:54:03,527.527] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-22 17:54:03,528.528] [               ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-22 17:54:03,528.528] [               ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-22 17:54:03,528.528] [               ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-22 17:54:03,534.534] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:54:03,535.535] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:54:04,553.553] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:54:05,567.567] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:54:06,582.582] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:54:07,605.605] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:54:08,620.620] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:54:09,636.636] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:54:10,650.650] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:54:11,669.669] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:54:11,670.670] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-22 17:54:11,671.671] [               ] Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")   (Logger.py:94)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 230, in _createConnectionPool
    recycle=self._connectionPoolRecyclingSeconds,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 121, in __init__
    con = ConnectionPool.__instance.connect()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 264, in <lambda>
    return lambda crec: creator()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 118, in getConnection
    return MySQLdb.connect(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 581, in __init__
    self._sql = MySQL(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 187, in __init__
    self._createConnectionPool()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 244, in _createConnectionPool
    raise BackendUnableToConnectError(u"Failed to connect to database '%s' address '%s': %s" % (self._database, address, error))
OPSI.Exceptions.BackendUnableToConnectError: Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")
[1] [2020-07-22 17:54:22,438.438] [               ] logger port: tests/test_data/output/opsipxeconfd.socket   (opsipxeconfd.py:785)
[3] [2020-07-22 17:57:12,615.615] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[1] [2020-07-22 17:57:12,615.615] [               ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-22 17:57:12,720.720] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:57:12,733.733] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-22 17:57:12,734.734] [               ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-22 17:57:12,734.734] [               ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-22 17:57:12,734.734] [               ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-22 17:57:12,736.736] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:57:12,737.737] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:57:13,750.750] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:57:14,764.764] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:57:15,778.778] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:57:16,793.793] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:57:17,808.808] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:57:18,825.825] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:57:19,842.842] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:57:20,856.856] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 17:57:20,858.858] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-22 17:57:20,858.858] [               ] Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")   (Logger.py:94)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 230, in _createConnectionPool
    recycle=self._connectionPoolRecyclingSeconds,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 121, in __init__
    con = ConnectionPool.__instance.connect()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 264, in <lambda>
    return lambda crec: creator()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 118, in getConnection
    return MySQLdb.connect(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 194, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 130, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 581, in __init__
    self._sql = MySQL(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 187, in __init__
    self._createConnectionPool()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 244, in _createConnectionPool
    raise BackendUnableToConnectError(u"Failed to connect to database '%s' address '%s': %s" % (self._database, address, error))
OPSI.Exceptions.BackendUnableToConnectError: Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")
[1] [2020-07-22 17:57:27,634.634] [               ] logger port: tests/test_data/output/opsipxeconfd.socket   (opsipxeconfd.py:785)
[3] [2020-07-22 17:57:27,637.637] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[3] [2020-07-22 17:57:27,637.637] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[3] [2020-07-22 18:00:11,853.853] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[1] [2020-07-22 18:00:11,853.853] [               ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-22 18:00:11,854.854] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:11,950.950] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:11,951.951] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-22 18:00:11,951.951] [               ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-22 18:00:11,952.952] [               ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-22 18:00:11,952.952] [               ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-22 18:00:11,968.968] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:11,969.969] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:12,986.986] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:14,000.000] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:15,018.018] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:16,035.035] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:17,052.052] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:18,071.071] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:19,086.086] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:20,116.116] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-22 18:00:20,117.117] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-22 18:00:20,117.117] [               ] Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")   (Logger.py:94)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 230, in _createConnectionPool
    recycle=self._connectionPoolRecyclingSeconds,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 121, in __init__
    con = ConnectionPool.__instance.connect()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 264, in <lambda>
    return lambda crec: creator()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 118, in getConnection
    return MySQLdb.connect(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 195, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 131, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 581, in __init__
    self._sql = MySQL(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 187, in __init__
    self._createConnectionPool()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 244, in _createConnectionPool
    raise BackendUnableToConnectError(u"Failed to connect to database '%s' address '%s': %s" % (self._database, address, error))
OPSI.Exceptions.BackendUnableToConnectError: Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")
[1] [2020-07-22 18:00:26,877.877] [               ] skipped init_logging. TODO: Rotating file handler   (opsipxeconfd.py:787)
[3] [2020-07-22 18:00:26,880.880] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[3] [2020-07-22 18:00:26,880.880] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[3] [2020-07-23 09:13:30,426.426] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[1] [2020-07-23 09:13:30,428.428] [               ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-23 09:13:30,582.582] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:13:30,582.582] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-23 09:13:30,583.583] [               ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-23 09:13:30,583.583] [               ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-23 09:13:30,583.583] [               ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-23 09:13:30,590.590] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:13:30,591.591] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:13:31,636.636] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:13:32,652.652] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:13:33,679.679] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:13:34,697.697] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:13:35,712.712] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:13:36,731.731] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:13:37,747.747] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:13:38,755.755] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:13:38,756.756] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-23 09:13:38,756.756] [               ] Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")   (Logger.py:94)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 230, in _createConnectionPool
    recycle=self._connectionPoolRecyclingSeconds,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 121, in __init__
    con = ConnectionPool.__instance.connect()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 264, in <lambda>
    return lambda crec: creator()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 118, in getConnection
    return MySQLdb.connect(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 195, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 131, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 581, in __init__
    self._sql = MySQL(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 187, in __init__
    self._createConnectionPool()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 244, in _createConnectionPool
    raise BackendUnableToConnectError(u"Failed to connect to database '%s' address '%s': %s" % (self._database, address, error))
OPSI.Exceptions.BackendUnableToConnectError: Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")
[1] [2020-07-23 09:13:45,444.444] [               ] skipped init_logging. TODO: Rotating file handler   (opsipxeconfd.py:787)
[3] [2020-07-23 09:13:45,446.446] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[3] [2020-07-23 09:13:45,446.446] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[3] [2020-07-23 09:17:43,024.024] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[1] [2020-07-23 09:17:43,025.025] [               ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-23 09:17:43,028.028] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:43,116.116] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:43,117.117] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-23 09:17:43,117.117] [               ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-23 09:17:43,117.117] [               ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-23 09:17:43,117.117] [               ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-23 09:17:43,120.120] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:43,120.120] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:44,137.137] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:45,153.153] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:46,165.165] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:47,178.178] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:48,203.203] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:49,216.216] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:50,229.229] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:51,247.247] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:17:51,248.248] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-23 09:17:51,248.248] [               ] Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")   (Logger.py:94)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 230, in _createConnectionPool
    recycle=self._connectionPoolRecyclingSeconds,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 121, in __init__
    con = ConnectionPool.__instance.connect()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 264, in <lambda>
    return lambda crec: creator()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 118, in getConnection
    return MySQLdb.connect(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 195, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 131, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 581, in __init__
    self._sql = MySQL(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 187, in __init__
    self._createConnectionPool()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 244, in _createConnectionPool
    raise BackendUnableToConnectError(u"Failed to connect to database '%s' address '%s': %s" % (self._database, address, error))
OPSI.Exceptions.BackendUnableToConnectError: Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")
[1] [2020-07-23 09:17:58,041.041] [               ] skipped init_logging. TODO: Rotating file handler   (opsipxeconfd.py:787)
[3] [2020-07-23 09:17:58,044.044] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[3] [2020-07-23 09:17:58,044.044] [               ] Logging error: name 'DEFAULT_COLORED_FORMAT' is not defined   (logging.py:139)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/logging.py", line 39, in init_logging
    opsicommon.logging.set_format(stderr_format = DEFAULT_COLORED_FORMAT)
NameError: name 'DEFAULT_COLORED_FORMAT' is not defined
[1] [2020-07-23 09:18:55,004.004] [               ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-23 09:18:55,006.006] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:18:55,090.090] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:18:55,091.091] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-23 09:18:55,091.091] [               ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-23 09:18:55,092.092] [               ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-23 09:18:55,092.092] [               ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-23 09:18:55,094.094] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:18:55,095.095] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:18:56,107.107] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:18:57,122.122] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:18:58,143.143] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:18:59,161.161] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:19:00,175.175] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:19:01,185.185] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:19:02,199.199] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:19:03,214.214] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:19:03,215.215] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-23 09:19:03,216.216] [               ] Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")   (Logger.py:94)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 230, in _createConnectionPool
    recycle=self._connectionPoolRecyclingSeconds,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 121, in __init__
    con = ConnectionPool.__instance.connect()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 264, in <lambda>
    return lambda crec: creator()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 118, in getConnection
    return MySQLdb.connect(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 195, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 131, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 581, in __init__
    self._sql = MySQL(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 187, in __init__
    self._createConnectionPool()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 244, in _createConnectionPool
    raise BackendUnableToConnectError(u"Failed to connect to database '%s' address '%s': %s" % (self._database, address, error))
OPSI.Exceptions.BackendUnableToConnectError: Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")
[1] [2020-07-23 09:19:10,024.024] [               ] skipped init_logging. TODO: Rotating file handler   (opsipxeconfd.py:787)
[1] [2020-07-23 09:20:03,520.520] [               ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-23 09:20:03,522.522] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:03,607.607] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:03,607.607] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-23 09:20:03,608.608] [               ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-23 09:20:03,608.608] [               ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-23 09:20:03,608.608] [               ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-23 09:20:03,610.610] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:03,610.610] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:04,624.624] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:05,638.638] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:06,655.655] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:07,672.672] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:08,687.687] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:09,704.704] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:10,722.722] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:11,740.740] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:20:11,742.742] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-23 09:20:11,742.742] [               ] Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")   (Logger.py:94)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 230, in _createConnectionPool
    recycle=self._connectionPoolRecyclingSeconds,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 121, in __init__
    con = ConnectionPool.__instance.connect()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 264, in <lambda>
    return lambda crec: creator()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 118, in getConnection
    return MySQLdb.connect(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 195, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 131, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 581, in __init__
    self._sql = MySQL(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 187, in __init__
    self._createConnectionPool()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 244, in _createConnectionPool
    raise BackendUnableToConnectError(u"Failed to connect to database '%s' address '%s': %s" % (self._database, address, error))
OPSI.Exceptions.BackendUnableToConnectError: Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")
[1] [2020-07-23 09:20:18,537.537] [               ] skipped init_logging. TODO: Rotating file handler   (opsipxeconfd.py:787)
[1] [2020-07-23 09:26:38,156.156] [               ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-23 09:26:38,157.157] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:38,254.254] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:38,255.255] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-23 09:26:38,255.255] [               ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-23 09:26:38,256.256] [               ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-23 09:26:38,256.256] [               ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-23 09:26:38,260.260] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:38,260.260] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:39,275.275] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:40,290.290] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:41,305.305] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:42,320.320] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:43,335.335] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:44,358.358] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:45,374.374] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:46,389.389] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:26:46,391.391] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-23 09:26:46,392.392] [               ] Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")   (Logger.py:94)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 230, in _createConnectionPool
    recycle=self._connectionPoolRecyclingSeconds,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 121, in __init__
    con = ConnectionPool.__instance.connect()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 264, in <lambda>
    return lambda crec: creator()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 118, in getConnection
    return MySQLdb.connect(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 195, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 131, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 581, in __init__
    self._sql = MySQL(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 187, in __init__
    self._createConnectionPool()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 244, in _createConnectionPool
    raise BackendUnableToConnectError(u"Failed to connect to database '%s' address '%s': %s" % (self._database, address, error))
OPSI.Exceptions.BackendUnableToConnectError: Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")
[1] [2020-07-23 09:26:53,173.173] [               ] skipped init_logging. TODO: Rotating file handler   (opsipxeconfd.py:787)
[1] [2020-07-23 09:27:12,373.373] [               ] opsi pxe configuration service starting   (opsipxeconfd.py:88)
[4] [2020-07-23 09:27:12,374.374] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:12,461.461] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:12,469.469] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:49: DeprecationWarning: OPSI.Logger.Logger is deprecated, use opsicommon.logging.logger instead.
  DeprecationWarning
   (warnings.py:110)
[3] [2020-07-23 09:27:12,470.470] [               ] No translation file found for language en_US, falling back to en_US   (ConfigData.py:1059)
[3] [2020-07-23 09:27:12,470.470] [               ] Failed to read translation file for language en_US: [Errno 2] No such file or directory: '/etc/opsi/hwaudit/locales/en_US'   (ConfigData.py:1074)
[4] [2020-07-23 09:27:12,470.470] [               ] Failed to read audit hardware configuration from file '/etc/opsi/hwaudit/opsihwaudit.conf': [Errno 2] No such file or directory: '/etc/opsi/hwaudit/opsihwaudit.conf'   (ConfigData.py:1145)
[4] [2020-07-23 09:27:12,476.476] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:12,482.482] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:13,496.496] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:14,510.510] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:15,528.528] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:16,557.557] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:17,578.578] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:18,599.599] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:19,618.618] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:20,632.632] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[4] [2020-07-23 09:27:20,633.633] [               ] /home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Logger.py:92: DeprecationWarning: OPSI.Logger.logException is deprecated, instead use logger.log with exc_info=True.
  DeprecationWarning
   (warnings.py:110)
[2] [2020-07-23 09:27:20,634.634] [               ] Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")   (Logger.py:94)
Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 230, in _createConnectionPool
    recycle=self._connectionPoolRecyclingSeconds,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 121, in __init__
    con = ConnectionPool.__instance.connect()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 264, in <lambda>
    return lambda crec: creator()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 118, in getConnection
    return MySQLdb.connect(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 195, in run
    self._createBackendInstance()
  File "/home/nils/Documents/opsipxeconfd/opsipxeconfd/opsipxeconfd.py", line 131, in _createBackendInstance
    extend=True
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/_Manager.py", line 181, in __init__
    self._backend = BackendDispatcher(context=self, **kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 79, in __init__
    self.__loadBackends(dict(kwargs))
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/Manager/Dispatcher.py", line 145, in __loadBackends
    self._backends[backend]["instance"] = getattr(b, backendClassName)(**cargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 581, in __init__
    self._sql = MySQL(**kwargs)
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 187, in __init__
    self._createConnectionPool()
  File "/home/nils/Documents/opsipxeconfd/.venv/lib/python3.7/site-packages/OPSI/Backend/MySQL.py", line 244, in _createConnectionPool
    raise BackendUnableToConnectError(u"Failed to connect to database '%s' address '%s': %s" % (self._database, address, error))
OPSI.Exceptions.BackendUnableToConnectError: Backend I/O error: Failed to connect to database 'opsi' address '127.0.0.1': (1045, "Access denied for user 'opsi'@'localhost' (using password: YES)")
